rate_limit_window: 10s  
rate_limit_count: 100 

services:
  driver:
    base_url: http://driver-service:8081 
    routes:
      - path: /drivers
      - path: /drivers/nearby
      - path: /drivers/{id}
     